### ISSUE TITLE
请问，我做缓存的时候问什么会崩溃

### ISSUE THREAD

**Issue by frankie9527** [laucherish/PureZhihuD#6]
我也是用okhttp+rxjava+retrofit 对数据进行缓存，但是如果没网的时候没有缓存就去读取数据就会返回504，然后就各种崩溃。。请问我该怎么办。。能留下qq联系方式吗？兄弟

**Comment by laucherish** [comment]
缓存一般由服务器控制(通过某些方式可以本地控制缓存，比如向过滤器添加缓存控制信息)。通过在请求头添加下面几个字端：

Request
请求头字段 意义
If-Modified-Since: Sun, 03 Jan 2016 03:47:16 GMT    缓存文件的最后修改时间。
If-None-Match: "3415g77s19tc3:0"    缓存文件的Etag(Hash)值
Cache-Control: no-cache 不使用缓存
Pragma: no-cache    不使用缓存

Response
响应头字段 意义
Cache-Control: public   响应被共有缓存，移动端无用
Cache-Control: private  响应被私有缓存，移动端无用
Cache-Control:no-cache  不缓存
Cache-Control:no-store  不缓存
Cache-Control: max-age=60   60秒之后缓存过期（相对时间）
Date: Sun, 03 Jan 2016 04:07:01 GMT 当前response发送的时间
Expires: Sun, 03 Jan 2016 07:07:01 GMT  缓存过期的时间（绝对时间）
Last-Modified: Sun, 03 Jan 2016 04:07:01 GMT    服务器端文件的最后修改时间
ETag: "3415g77s19tc3:0" 服务器端文件的Etag[Hash]值
正式使用时按需求也许只包含其中部分字段。
客户端要根据这些信息储存这次请求信息。

laucherish@gmail.com
